services:

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  ollama:
    image: ollama/ollama
    container_name: ollama
    gpus: all
    ports:
      - "11434:11434"
    volumes:
      - ./ollama:/root/.ollama
    restart: unless-stopped


  backend:
    build: ./backend
    container_name: backend
    gpus: all
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      - OLLAMA_API_HOST=${OLLAMA_API_HOST}
      - HF_HOME=${HF_HOME}
      - LOG_LEVEL=${LOG_LEVEL}
      - DEBUG=${DEBUG}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - ollama
      - mariadb
    volumes:
      - ./app:/backend/app
      - ./config:/etc/backend
      - ./documents:/backend/documents
      - ./faiss_data:${FAISS_DIR}
      - ./frontend:/backend/frontend
      - ./models:${HF_HOME}
      - ./logs:/backend/logs
      - .env:/backend/.env
    restart: unless-stopped
